version: '3.1'

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ist_db
      MYSQL_USER: ist
      MYSQL_PASSWORD: qwerty